### ISSUE TITLE
The Mudkip line isnt working for the stats screen

### ISSUE THREAD

**Issue by EpsilonXY** [gatekeep06/Cobblenav-Legacy#51]
whenever you go into the stats screen with the pokenav, the area where your starter should be is invisible if you chose mudkip or any of the evolution line
![image](https://github.com/user-attachments/assets/43257421-a543-45f2-a691-62fd1a709fc0)
![image](https://github.com/user-attachments/assets/ee6a8489-aa52-4753-8d14-e2a3d0018479)

**Comment by gatekeep06** [comment]
This area doesn't show the starter, but the most frequently used pokemon in battle, so maybe you just haven't used mudkip once

**Comment by EpsilonXY** [comment]
ohh I didnt know that. I was in a creative world so I just thought it was your starter that appears there. Thanks for the info!
