### ISSUE TITLE
"There doesn't seem to be anything living here" message in Pokenav

### ISSUE THREAD

**Issue by Zitroneo** [gatekeep06/Cobblenav-Legacy#53]
Hey, sorry I know github is probably not the right place to ask this question but I don't know where else to go.
The discord link on https://modrinth.com/mod/cobblemon-pokenav links to a channel I cannot look at.

I installed Cobblemon Pokenav on my existing "BigChadGuys Plus (w Cobblemon) installation on Curseforge and crafted the Pokefinder and Pokenav. The Pokenav only displays "There doesn't seem to be anything living here" under locations regardless where I am and the Pokefinder only says "You have no saved pokemon". 

Do you have an idea why the Nav doesn't find anything? I assume it maybe has problems with the biomes?
Sorry again if this is the wrong place, but like I said the discord link just displays and unreadable channel for me.

EDIT: I set "useCobbledexIntegration", "onlySeenPokemonMode" and "useCobblemonTrainersIntegration" to true in the cobblenav-config.json but left checkSpawnWidth and Height on -1. Could anything of this be related?

**Comment by gatekeep06** [comment]
Have you interacted with any pokemon? onlySeenPokemonMode blocks the display of those you haven't seen yet, using systems from Cobbledex or Counter

**Comment by Zitroneo** [comment]
I did interact with a lot of pokemon before and after adding the mod but removing "onlySeenPokemonMode" did fix my issue! Thank you for your help!
